//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalibrationSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GaugeMaster
    {
        public int ID { get; set; }
        public string GaugeName { get; set; }
        public string GaugeItemCode { get; set; }
        public string GaugeType { get; set; }
        public Nullable<decimal> GaugeDimAndTolerance { get; set; }
        public string ComponentDetails { get; set; }
        public string GaugeDrawing { get; set; }
        public string CalibrationScheduling { get; set; }
        public string GaugeMaterial { get; set; }
    }
}
