//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalibrationSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMaster
    {
        public int ID { get; set; }
        public string DrawingNo { get; set; }
        public string Version { get; set; }
        public string C_Index { get; set; }
        public string PartName { get; set; }
        public string PartCode { get; set; }
        public string PartCategory { get; set; }
        public string CustomerName { get; set; }
        public string DrawingUpload { get; set; }
        public string ControlPlanUpload { get; set; }
        public string PPAPUpload { get; set; }
        public string BallooningNumber { get; set; }
    }
}
