//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalibrationSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMasterDetail
    {
        public int ID { get; set; }
        public Nullable<int> ItemMasterID { get; set; }
        public string BaseValue { get; set; }
        public string LTol { get; set; }
        public string UTol { get; set; }
        public string TypeOfGauge { get; set; }
        public string CalibrationFrequency { get; set; }
        public string Location { get; set; }
        public string Inward { get; set; }
        public string Production { get; set; }
        public string QualityRoomLineInspection { get; set; }
        public string FinalInspection { get; set; }
        public string BallooningNumber { get; set; }
    }
}
