//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalibrationSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasuringInstrumentMaster
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DateOfPurchase { get; set; }
        public string TypeOfInstrument { get; set; }
        public string Specifications { get; set; }
        public string GaugeManufacturerID { get; set; }
        public string GaugeInternalID { get; set; }
        public string ManufacturerName { get; set; }
        public string SupplierName { get; set; }
        public string Price { get; set; }
        public string InspectionCalibrationReport { get; set; }
        public string GaugeStatus { get; set; }
        public string CalibrationFrequency { get; set; }
        public string DrawingOrOtherDocuments { get; set; }
        public string ManualAttachment { get; set; }
    }
}
