//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalibrationSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Rights { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string EmailId { get; set; }
        public string Department { get; set; }
        public string ContactNo { get; set; }
    }
}
